rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx-2.1.1
gemfile:
  - active_support_3_2
  - active_support_4_0
before_script:
  - sudo sh -c 'echo "[native_query_servers]" >> /etc/couchdb/local.ini'
  - sudo sh -c 'echo "erlang = {couch_native_process, start_link, []}" >> /etc/couchdb/local.ini'
  - sudo /etc/init.d/couchdb restart
matrix:
  allow_failures:
    - rvm: jruby-19mode
